version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - dev-networks
    environment:
      PORT: ${PORT}
      RIOT_API_KEY: ${RIOT_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}

  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dev-networks
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
      PORT: ${PORT}
      RIOT_API_KEY: ${RIOT_API_KEY}

volumes:
  dev-postgres-data:

networks:
  dev-networks-data:
